# docs/api_spec.yaml
openapi: 3.0.3
info:
  title: VisionGuard Parking API
  version: 1.2.0
  description: |
    API for smart parking management system with NFT integration
servers:
  - url: https://api.visionguard.io/v1
    description: Production server

paths:
  /parking/entry:
    post:
      tags: [Parking]
      summary: Process vehicle entry
      operationId: processVehicleEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleEntry'
      responses:
        201:
          description: NFT minted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFTResponse'
        429:
          description: Parking lot at capacity
          
  /parking/{nftId}/exit:
    post:
      tags: [Parking]
      summary: Process vehicle exit
      parameters:
        - name: nftId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Exit processed successfully
        404:
          description: NFT not found

components:
  schemas:
    VehicleEntry:
      type: object
      required: [licensePlate, vehicleType]
      properties:
        licensePlate:
          type: string
          pattern: '^[A-Z0-9]{2,10}$'
          example: "KAA123X"
        vehicleType:
          type: string
          enum: [sedan, suv, truck, motorcycle]
        timestamp:
          type: string
          format: date-time
          description: Entry time in UTC

    NFTResponse:
      type: object
      properties:
        nftId:
          type: string
          format: uuid
        transactionHash:
          type: string
          pattern: '^0x[a-fA-F0-9]{64}$'
        parkingFee:
          type: number
          format: float
          minimum: 0
        validUntil:
          type: string
          format: date-time